export const appPath = {
  HOME: '/',
  ADMIN: '/admin',
  LOGIN: '/auth/login',
};

export const adminPath = {
  DASHBOARD: '/admin',
  ROLES: '/admin/roles',
  USERS: '/admin/users',
  USERS_STUDENTS: '/admin/users/students',
  USERS_ORGANIZERS: '/admin/users/organizers',
  PERMISSIONS: '/admin/permissions',
  CRITERIA: '/admin/criterias',
  CRITERIA_FRAME: '/admin/criteria-version-management',
  FACULTIES: '/admin/academic/faculties',
  MAJORS: '/admin/academic/majors',
  CLASSES: '/admin/academic/classes',
  EVENT_MANAGEMENT: '/admin/event-management',
  EVENT_DETAIL: '/admin/event-management/[eventId]',
  EVENT_CATEGORIES: '/admin/event-categories',
  EVENT_TEMPLATES: '/admin/event-templates',
  ACADEMIC_YEAR: '/admin/academic-year',
  SEMESTERS: '/admin/semesters',
  STUDENTS: '/admin/students',
  STUDENT_SCORE: '/admin/student-scores',
};

export const TabHeaderName: Record<string, string> = {
  '/admin': 'Tổng quan',
  '/admin/users': 'Quản Lý Người Dùng',
  '/admin/users/students': 'Quản Lý Sinh Viên',
  '/admin/users/organizers': 'Quản Lý Ban Tổ Chức',
  '/admin/permissions': 'Quản Lý Quyền Hạn',
  '/admin/roles': 'Quản Lý Vai Trò',
  '/admin/criterias': 'Quản Lý Tiêu Chí',
  '/admin/criteria-version-management': 'Quản Lý Tiêu Chí',
  '/admin/academic/faculties': 'Quản Lý Khoa',
  '/admin/academic/majors': 'Quản Lý Ngành',
  '/admin/academic/classes': 'Quản Lý Lớp',
  '/admin/event-management': 'Quản Lý Sự Kiện',
  '/admin/event-management/create': 'Tạo Sự Kiện Mới',
  '/admin/event-categories': 'Quản Lý Danh Mục Sự Kiện',
  '/admin/event-templates': 'Quản Lý Mẫu Sự Kiện',
  '/admin/events': 'Tạo Sự Kiện',
  '/admin/academic-year': 'Quản Lý Năm Học',
  '/admin/semesters': 'Quản Lý Học Kỳ',
  '/admin/students': 'Quản Lý Sinh Viên',
  '/admin/student-scores': 'Quản Lý Điểm Rèn Luyện',
  '/admin/event-management/participants': 'Quản Lý Tham Gia',
  '/admin/event-management/attendances': 'Duyệt Điểm Danh',
};
